[package]
name = "nia_basic_assertions"
version = "0.1.0"
authors = ["Emirayka"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "0.6.1"
float-cmp = "0.7.0"
